name:                steves-modules
version:             0.1.0.0
github:              "stevemao/steves-modules"
license:             BSD3
author:              "Steve Mao"
maintainer:          "maochenyan@gmail.com"
copyright:           "2019 Steve Mao"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Steve's modules
category:            Utils, String

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stevemao/steves-modules#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall  

tests:
  steves-modules-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - steves-modules
